from amazoncorretto:17-alpine as builder
workdir /app

copy ./.mvn ./.mvn
copy ./mvnw .
run chmod +x ./mvnw
copy ./pom.xml .

run ./mvnw dependency:go-offline

copy ./src ./src
run ./mvnw clean package -DskipTests

from amazoncorretto:17-alpine
workdir /app
copy --from=builder /app/target/controlgastos-0.0.1-SNAPSHOT.jar .

expose 7000
entrypoint ["java", "-jar", "controlgastos-0.0.1-SNAPSHOT.jar"]