server.port=${LOCAL_DK_SERVER_PORT}

logging.level.com.alejandro.controlgastos=DEBUG

# Configuration for MongoDB connection
spring.data.mongodb.host=${LOCAL_DK_HOST_NAME}
spring.data.mongodb.port=27017
spring.data.mongodb.database=${LOCAL_DK_DB_NAME}

logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb=DEBUG
logging.level.org.mongodb.driver.cluster=INFO

# Configuration for Redis connection
spring.data.redis.host=${LOCAL_DK_REDIS_CONTAINER_NAME}
spring.data.redis.port=${LOCAL_DK_REDIS_PORT}
spring.data.redis.password=${LOCAL_DK_REDIS_PASSWORD}
spring.data.redis.timeout=500ms

logging.level.org.springframework.data.redis.core=DEBUG
logging.level.org.springframework.data.redis.connection=DEBUG

# Configuration for Circuit Breaker
resilience4j.circuitbreaker.instances.redisRemoteCB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.redisRemoteCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.redisRemoteCB.waitDurationInOpenState=30s
resilience4j.circuitbreaker.instances.redisRemoteCB.permittedNumberOfCallsInHalfOpenState=3 